#!/bin/bash -e

LOG_DIR=/var/vcap/sys/log/orientdb
ORIENTDB_SCRIPT=/var/vcap/packages/orientdb/bin/orientdb.sh

make_log_dir() {
  mkdir -p $LOG_DIR
  chown vcap:vcap $LOG_DIR
}

configure_orientdb_script() {
  script_path="$1"

  sed -e \
    's#ORIENTDB_DIR="YOUR_ORIENTDB_INSTALLATION_PATH"#ORIENTDB_DIR=/var/vcap/packages/orientdb#g' \
    <<< \
  sed -e \
    's#ORIENTDB_USER="USER_YOU_WANT_ORIENTDB_RUN_WITH"#ORIENTDB_USER=vcap#g' \
    "${script_path}"
}

main() {
  make_log_dir
  configure_orientdb_script "${ORIENTDB_SCRIPT}" > "${ORIENTDB_SCRIPT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
