#!/bin/bash -e

LOG_DIR=/var/vcap/sys/log/orientdb

make_log_dir() {
  mkdir -p $LOG_DIR
  chown vcap:vcap $LOG_DIR
}

update_orientdb_script() {
  sed -i -e \
    's#ORIENTDB_DIR="YOUR_ORIENTDB_INSTALLATION_PATH"#ORIENTDB_DIR=/var/vcap/packages/orientdb#g' \
    /var/vcap/packages/orientdb/bin/orientdb.sh

  sed -i -e \
    's#ORIENTDB_USER="USER_YOU_WANT_ORIENTDB_RUN_WITH"#ORIENTDB_USER=vcap#g' \
    /var/vcap/packages/orientdb/bin/orientdb.sh
}

main() {
  make_log_dir
  update_orientdb_script
}

main
