#!/bin/bash -e

LOG_DIR="/var/vcap/sys/log/orientdb"

ORIENTDB_USER="vcap"
ORIENTDB_INSTALL_DIR="/var/vcap/packages/orientdb"
ORIENTDB_TEMPLATE="${ORIENTDB_INSTALL_DIR}/bin/orientdb.sh.template"

make_log_dir() {
  mkdir -p $LOG_DIR
  chown vcap:vcap $LOG_DIR
}

template_orientdb_script() {
  if [[ $# -ne 3 ]]; then
    echo "expected 3 arguments with call to template_orientdb_script" 1>&2
    return 1
  fi

  template="$1"
  install_dir="$2"
  user="$3"

  sed -e \
    "s#YOUR_ORIENTDB_INSTALLATION_PATH#${install_dir}#g" \
    <<< \
  sed -e \
    "s#USER_YOU_WANT_ORIENTDB_RUN_WITH#${user}#g" \
    "${template}"
}

main() {
  make_log_dir

  template_orientdb_script \
    "${ORIENTDB_TEMPLATE}" \
    "${ORIENTDB_INSTALL_DIR}" \
    "${ORIENTDB_USER}" \
  > "${ORIENTDB_INSTALL_DIR}/bin/orientdb.sh"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
